# Generated by Django 3.1.3 on 2020-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdressing',
            name='adding_mage_1',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Добавочная фотография'),
        ),
    ]
