# Generated by Django 3.1.3 on 2020-12-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0003_auto_20201129_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hairdressing',
            options={'verbose_name': 'Hairdressing'},
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Район', to='parikmaherMD.area'),
        ),
    ]
