# Generated by Django 3.1.3 on 2021-01-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0004_auto_20201227_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairdressing',
            old_name='adding_mage_1',
            new_name='adding_image_1',
        ),
        migrations.RemoveField(
            model_name='hairdressing',
            name='adding_image_3',
        ),
    ]
