# Generated by Django 3.1.3 on 2021-01-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0005_auto_20210102_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdressing',
            name='schedule_for_clients',
        ),
    ]
