# Generated by Django 3.1.3 on 2021-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0006_remove_hairdressing_schedule_for_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='reviews',
            field=models.URLField(blank=True, max_length=300, verbose_name='Отзывы'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='website',
            field=models.URLField(blank=True, max_length=300, verbose_name='Сайт'),
        ),
    ]
