# Generated by Django 3.1.3 on 2021-01-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0007_auto_20210103_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='friday',
            field=models.TextField(default='', verbose_name='Пятница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='monday',
            field=models.TextField(default='', verbose_name='Понедельник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='saturday',
            field=models.TextField(default='', verbose_name='Суббота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='sunday',
            field=models.TextField(default='', verbose_name='Воскресенье'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='thursday',
            field=models.TextField(default='', verbose_name='Четверг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='tuesday',
            field=models.TextField(default='', verbose_name='Вторник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='wednesday',
            field=models.TextField(default='', verbose_name='Среда'),
            preserve_default=False,
        ),
    ]
