# Generated by Django 3.1.3 on 2021-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0008_auto_20210103_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdressing',
            name='friday',
            field=models.CharField(max_length=200, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='monday',
            field=models.CharField(max_length=200, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='saturday',
            field=models.CharField(max_length=200, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='sunday',
            field=models.TextField(max_length=200, verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='thursday',
            field=models.CharField(max_length=200, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='tuesday',
            field=models.CharField(max_length=200, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='wednesday',
            field=models.CharField(max_length=200, verbose_name='Среда'),
        ),
    ]
