# Generated by Django 3.1.3 on 2021-01-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0009_auto_20210103_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdressing',
            name='sunday',
            field=models.CharField(max_length=200, verbose_name='Воскресенье'),
        ),
    ]
