# Generated by Django 3.1.3 on 2021-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0010_auto_20210103_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdressing',
            name='specializations',
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='manicure',
            field=models.TextField(blank=True, verbose_name='Маникюр'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='services_for_face_and_body',
            field=models.TextField(blank=True, verbose_name='Услуги для лица и тела'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='services_for_fingernails',
            field=models.TextField(blank=True, verbose_name='Услуги для ногтей'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='services_for_hair',
            field=models.TextField(blank=True, verbose_name='Услуги для волос'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='type_of_salon',
            field=models.TextField(blank=True, verbose_name='Тип салона'),
        ),
    ]
