# Generated by Django 3.1.3 on 2021-01-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0011_auto_20210107_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdressing',
            name='price_list',
        ),
    ]
