# Generated by Django 3.1.3 on 2021-02-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0012_remove_hairdressing_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='eye_contour',
            field=models.TextField(blank=True, verbose_name='Контур глаз'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='tattoo',
            field=models.TextField(blank=True, verbose_name='Тату'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='tattoo_and_microblading',
            field=models.TextField(blank=True, verbose_name='Тату и микроблэдинг'),
        ),
    ]
