# Generated by Django 3.1.3 on 2021-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0013_auto_20210213_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdressing',
            name='friday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='monday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='saturday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='schedule_for_calculating',
            field=models.TextField(blank=True, verbose_name='Расписание(для расчёта)'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='sunday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Воскресенье'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='thursday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='tuesday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Вторник'),
        ),
        migrations.AlterField(
            model_name='hairdressing',
            name='wednesday',
            field=models.CharField(blank=True, max_length=200, verbose_name='Среда'),
        ),
    ]
