# Generated by Django 3.1.3 on 2021-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0014_auto_20210213_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='work_graphic',
            field=models.CharField(blank=True, max_length=500, verbose_name='График работы'),
        ),
    ]
