# Generated by Django 3.1.3 on 2021-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0015_hairdressing_work_graphic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdressing',
            name='tattoo_and_microblading',
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='tattooash_and_microblading',
            field=models.TextField(blank=True, verbose_name='Татуаж и микроблэдинг'),
        ),
    ]
