# Generated by Django 3.1.3 on 2021-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0016_auto_20210213_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdressing',
            name='tattoo',
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='other',
            field=models.TextField(blank=True, verbose_name='Другое'),
        ),
    ]
