# Generated by Django 3.1.3 on 2021-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parikmaherMD', '0018_auto_20210214_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressing',
            name='cosmetology',
            field=models.TextField(blank=True, verbose_name='Косметология'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='permanent',
            field=models.TextField(blank=True, verbose_name='Перманент'),
        ),
        migrations.AddField(
            model_name='hairdressing',
            name='services_for_eyelashes',
            field=models.TextField(blank=True, verbose_name='Услуги для ресниц'),
        ),
    ]
